### ISSUE TITLE
Middleware stops responding when wrong cashbox id sent

### ISSUE THREAD

**Issue by darek-phorest** [fiskaltrust/middleware-interface-dotnet#24]
Hi is there any way to improve the middleware as it currently stops responding when we sent a message to the rest queue which contains cashbox id which the middleware is not configured for. 
We have to restart the middleware service to fix it.

**Comment by StefanKert** [comment]
Hi @darek-phorest,

Is it possible for you to provide additional information like the cashboxid, the version of the launcher and the configuration that you are using?

Additionally it would be amazing if you could provide us with the log that the launcher (fiskaltrust.exe) is showing. If you use the launcher with verbosity debug you should see further details :)

Thanks a lot for your help :)

**Comment by TSchmiedlechner** [comment]
Hi! We just noticed that this is a general bug in the Launcher 1.3.5, thank you very much for reporting this. We'll fix it as soon as possible and update you about the state here.

**Comment by TSchmiedlechner** [comment]
Hi @darek-phorest, thanks again for reporting this. We resolved this issue in version 1.3.6, which was deployed to production a few minutes ago.
