### ISSUE TITLE
.NET synchrone pos.Sign() Methode?

### ISSUE THREAD

**Issue by DS-DEV678** [fiskaltrust/middleware-interface-dotnet#28]
Ich habe in FT lib eine sign Methode gesehen, die scheinbar synchron ablaufen sollte.
Diese ist allerdings deprecated, wie soll ich das deuten?

**Wir benötigen dringend eine synchronene Aufrufmöglichkeit**,
da sonst alle unsere Prozesse unnötig verkompliziert werden, wohl auch nicht der sinn einer MW
Schätze dies hilft auch anderen Herstellern!

Ein async Call ist an dieser Stelle auch völlig sinnlos!

**Comment by TSchmiedlechner** [comment]
Hallo @DS-DEV678,
wir orientieren uns bei unserem API-Design an der gängigen Praxis und Industriestandards, und in diesen wird bei Calls zu externen Depenendencies z.B. über TCP oder andere Sockets mittlerweile einhellig die Verwendung asynchroner Methoden empfohlen, um z.B. das User Interface nicht zu blockieren.

Falls die Verwendung von asynchronen Methoden in Ihrem Szenario nicht möglich ist, haben Sie folgende Optionen:
- Weiterhin die synchronenen Methoden verwenden
- `pos.EchoAsync(...).Result`, bzw. falls dieser Call in Ihrem Szenario ein Deadlock auslöst `Task.Run(async () => pos.EchoAsync(...)).Result`
- Die selbstständige Implementierung des Interfaces via nicht-blockierende HTTP-Calls.

Hoffentlich erfüllt eine dieser Möglichkeiten Ihre Anforderungen.
