### ISSUE TITLE
CryptoVision Hardware TSE - SDK Variante

### ISSUE THREAD

**Issue by DS-DEV678** [fiskaltrust/middleware-interface-dotnet#29]
wie kann ich die CryptoVision Hardware TSE - SDK Variante via .NET zurücksetzen?

**Comment by TSchmiedlechner** [comment]
Hallo,
unsere Middleware bzw. unser Client beinhaltet keine Funktionalität zum Zurücksetzen von Dev-TSEs. CryptoVision legt allerdings ein Tool bei, das Sie unter folgendem Pfad finden können:
`<TSE-Laufwerk>:\factory-reset\factoryReset.jar`

Der Aufruf erfolgt so:
`java -jar factoryReset.jar`

Diese Call könnten Sie z.B. ja auch relativ einfach aus einem .NET-Programm als externen Prozess aufrufen.
