### ISSUE TITLE
Dauer und Timeouts für ReceiptJournals

### ISSUE THREAD

**Issue by DS-DEV678** [fiskaltrust/middleware-interface-dotnet#30]
für Abfrage des ReceiptJournals mit 10 entries braucht es 30 sek, wie kann das sein?
was hängt hier schief, eine idee?
wie hoch sollte man die Timeouts setzen?

**Comment by TSchmiedlechner** [comment]
Hallo,
30 Sekunden sind definitiv zu lang, möglicherweise handelt es sich um einen Bug. Könnten Sie bitte die Cashbox-ID und den genauen Aufruf des ReceiptJournal-Endpunkts posten? Welches Kommunikationsprotokoll verwenden Sie?

**Comment by TSchmiedlechner** [comment]
Ich schließe den Issue mal; falls das Problem noch besteht, können wir hier jederzeit wieder öffnen. Danke!
