### ISSUE TITLE
.NET JournalRequest Format unklar für From & To, Long=Ticks???

### ISSUE THREAD

**Issue by DS-DEV678** [fiskaltrust/middleware-interface-dotnet#32]
Info nicht auffindbar welches Datums-Format hier verendet werden soll?
pos.JournalAsync(new JournalRequest { ftJournalType = (long)journalCase, From=(???)dtFrom, To=(???)dtTo

**Comment by TSchmiedlechner** [comment]
Hallo,
genau, die Methode erwartet .NET Ticks.
Vielen Dank auch für den Hinweis, wir werden unsere Dokumentation diesbezüglich verbessern.
