### ISSUE TITLE
.NET JournalExport DSFinVKFile Formate

### ISSUE THREAD

**Issue by DS-DEV678** [fiskaltrust/middleware-interface-dotnet#33]
was ist bei DSFinVKFile Export das Dateiformat, Encoding, gibts ein sample?

TSETARFile = 4919338167972134913,	//TAR-File from TSE device
DSFinVKFile = 4919338167972134914,	//DSFinV-K-File 	1.3.6
TARFile = 4919338167972134915		//TAR-File 	1.3.11

**Comment by TSchmiedlechner** [comment]
Hallo,
es handelt sich um ein .ZIP-File. Wir haben unsere Dokumentation diesbezüglich gerade upgedated.

Gleich an dieser Stelle auch ein Hinweis: Falls sie REST oder SOAP mit der `JournalAsync()`-Methode verwenden, gab es einen Bug im Client, der dazu führt dass das Zip-File nicht von allen Programmen gelesen richtig gelesen werden kann. Dieser Fehler wurde im Client 1.3.5 gefixed, der heute released wird.

**Comment by DS-DEV678** [comment]
danke für die Info. bitte bei updates auch alle komponenten mit strongnames zur verfügung stellen, danke.

**Comment by TSchmiedlechner** [comment]
Die Packages wurden released, hier das HTTP.StrongName:
https://www.nuget.org/packages/fiskaltrust.Middleware.Interface.Client.Http.StrongName
