### ISSUE TITLE
Fragen 23.11.2020

### ISSUE THREAD

**Issue by DS-DEV678** [fiskaltrust/middleware-interface-dotnet#34]
Wir stehen kurz vor dem Rollout und es sind noch einige Fragen offen!
Es wäre hilfreich mit jemanden von euch telefonieren zu können.

1.	wir arbeiten nur mit der .NET http Klasse und der CryptoVision Hardware TSE, welche URLs braucht es in der Portal-Config?
reicht die rest, oder muss auch die soap url inkludiert werden?

2.	Wie sollen wir mit dem Port Chaos umgehen?
http://localhost:1500/c8228e2a-94cd-41d3-b1fc-f18625645946 aus 1200 wird 1500

3.	FT MW Adressierung im Netzwerk (mit zentralem Server) via IP und PC-Name möglich?

4.	Firewall Definition – müssen für FT MW Ausnahmen definiert werden? Wenn ja welche?

5.	Welche Rolle spielt der AccessToken bei der Hardware TSE, bei auto Rollouts scheint es notwendig zu sein?

wenn mit 3 eigenständigen bizsoft kassen arbeiten (eigenen ID, eigener kassenstand, eigene BonNrKreis)
schreiben diese in eine cashbox und eine queue?

**Comment by TSchmiedlechner** [comment]
Hallo,
1. In dem Fall können Sie die Komponenten ausschließlich mit REST konfigurieren, kein Problem
2. Die Frage versteh ich leider nicht ganz - 1200 ist bei uns der Standard-Port für SOAP/HTTP, 1500 wird standardmäßig für REST eingesetzt. Das ist aber nur die Voreinstellung, Sie können auch jeden anderen Port konfigurieren.
3. Ja, grundsätzlich möglich. Damit sich die Middleware an Public-Adressen bindet, müssen Sie aber die IP bzw. den Rechnernamen in der URL konfigurieren (statt `rest://localhost...`) - normalerweise aber nur für die Queue, sofern SCU und Queue am gleichen Rechner laufen.
4. Das hängt stark von Ihrer Firewall ab. Sie verwenden REST, also wird der konfigurierte Port (default: 1500) vermutlich freizugeben sein (nur TCP, kein UDP nötig). Die Windows-Firewall fragt, soweit ich das im Kopf habe, beim Start nach falls noch nichts konfiguriert ist.
5. Das Access Token wird verwendet, um die Cashbox für den Konfigurations-Download und den Daten-Upload auf unseren Servern zu authentifizieren

Die letzte Frage ist sehr architekturabhängig. Sie können entweder pro physicher Kasse eine eigene Cashbox und Queue konfigurieren, oder mit einer Cashbox/einer Queue arbeiten und die Kassen als Terminals betreiben. Wir haben zu den möglichen Szenarien eine recht umfangreiche Doku: https://docs.fiskaltrust.cloud/doc/productdescription-de-doc/for-posdealers/02-pre-sales/rollout-scenarios.html

Ich hoffe, das klärt Ihre Fragen mal soweit - falls nicht, würd ich Sie bitten sich mit Ihren Kontaktdaten per Mail an support@fiskaltrust.de zu wenden um dort einen Termin mit unseren Rollout-Experten zu organisieren.
