### ISSUE TITLE
Fiskaltrust Middleware installation issue on macOS starting from 10.11 

### ISSUE THREAD

**Issue by anceschim** [fiskaltrust/middleware-interface-dotnet#39]
We need to install the middleware on OSX/macOS environment (on different versions, starting from 10.9 to the latest).

Of course, we followed the directions for Unix-like systems, but on all OSX version (from 10.11) Apple introduced SIP ([System Integrity Protection](https://en.wikipedia.org/wiki/System_Integrity_Protection)); this mechanism deny every user modification on a documented set of directories/subtrees.
This is a blocking factor here, because SIP deny permissions to write everywhere under /usr directory; so, neither the program nor we (in a manual way) can create the directory /usr/share/fiskaltrust, as per Linux [documentation](https://docs.fiskaltrust.cloud/docs/poscreators/middleware-doc/general/installation).

Please note that (by SIP design) there's no way to write here, no matter the user we log in (not even with admin/root users).

There's an option to specify an alternative location of /usr/share/fiskaltrust? (other paths are reachable with SIP, so this wouldn't be a problem, if it's configurable).

**Comment by TSchmiedlechner** [comment]
Hi @anceschim,
again, thanks for your request! As described in #40, you can specify the service folder via the `-servicefolder` parameter of the `fiskaltrust.exe` - as described [here](https://docs.fiskaltrust.cloud/docs/poscreators/middleware-doc/general/installation). 🙂
