### ISSUE TITLE
How to get TSE-ID?

### ISSUE THREAD

**Issue by doczoidberg** [fiskaltrust/middleware-interface-dotnet#43]
Is it possible to get the TSE-Serial Number via the middleware?

How can I set `<kassen-seriennummer>` ?
And what is the difference between cbTerminalID and kassen-seriennummer?

**Comment by fiscoal** [comment]
A zero receipt should get you that information.

> In addition, the response also contains a detailed status information about the used TSE-Device. TSE data is herefore loaded and that may cause a long running request.

https://docs.fiskaltrust.cloud/docs/poscreators/middleware-doc/germany/reference-tables/ftreceiptcase

The field in question should be `SerialNumberOctet`.
